"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function SuccessPage() {
  const [docReady, setDocReady] = useState(false);

  useEffect(() => {
    // Simulate backend doc creation
    const timer = setTimeout(() => setDocReady(true), 4000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-green-50 to-white text-gray-800 p-6">
      <section className="bg-white p-10 rounded-2xl shadow-lg max-w-lg w-full text-center">
        <h1 className="text-3xl font-bold text-green-700 mb-4">
          ✅ Payment Successful!
        </h1>
        <p className="text-gray-600 mb-6">
          Thank you for trusting <strong>QuickLegalBiz</strong>. Your document is being generated by our Legal Process System.
        </p>

        {!docReady ? (
          <>
            <p className="text-gray-500 mb-4">Generating your motion document...</p>
            <div className="w-full bg-gray-200 rounded-full h-3">
              <div className="bg-green-600 h-3 rounded-full w-3/4 animate-pulse"></div>
            </div>
          </>
        ) : (
          <>
            <p className="text-gray-700 mb-4">
              Your document is ready! You can download it or view it now.
            </p>
            <div className="flex justify-center gap-4">
              <a
                href="/docs/sample-motion.pdf"
                download
                className="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition"
              >
                📄 Download Motion
              </a>
              <Link
                href="/support"
                className="bg-gray-100 text-gray-700 px-6 py-2 rounded-lg hover:bg-gray-200"
              >
                Contact Support
              </Link>
            </div>
          </>
        )}

        <p className="mt-6 text-sm text-gray-500">
          Supported by Legal Process Specialists — here to make sure your filing is successful.
        </p>
      </section>
    </main>
  );
}